mysql -u root -p${MYSQL_ROOT_PASSWORD} << EOS
CREATE DATABASE keycloak CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE USER IF NOT EXISTS ${KEYCLOAK_DB_USER} IDENTIFIED BY '${KEYCLOAK_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON keycloak.* TO '${KEYCLOAK_DB_USER}'@'%' WITH GRANT OPTION;
EOS
