mysql -u root -p${MYSQL_ROOT_PASSWORD} << EOS
CREATE DATABASE ${APP1_DB_NAME} CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE USER IF NOT EXISTS ${APP1_DB_USER} IDENTIFIED BY '${APP1_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON ${APP1_DB_NAME}.* TO '${APP1_DB_USER}'@'%' WITH GRANT OPTION;

CREATE TABLE IF NOT EXISTS ${APP1_DB_NAME}.records (
    id         INT AUTO_INCREMENT PRIMARY KEY  COMMENT 'ID',
    uid        VARCHAR(48) NOT NULL            COMMENT 'ユーザーID',
    issue      TINYINT     NOT NULL            COMMENT '勝敗（0:勝ち、1:負け、2:引き分け）',
    type       TINYINT     NOT NULL            COMMENT 'ユーザーが出した手（0:グー、1:チョキ、2:パー）',
    comment    VARCHAR(48) NOT NULL DEFAULT '' COMMENT '備考',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
) COMMENT = '勝敗履歴'
;
EOS
